# Generated by Django 3.2.3 on 2021-05-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200730_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebook',
            new_name='Games',
        ),
    ]
