# Generated by Django 3.2.3 on 2021-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_games_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='game',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='processor_freq',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_without_charge',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video',
        ),
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.CharField(default='Default', max_length=255, verbose_name='Издатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='default', max_length=255, verbose_name='Жанр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.CharField(default=1, max_length=255, verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(default=' ', max_length=255, verbose_name='Платформа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='relise',
            field=models.CharField(default=' ', max_length=255, verbose_name='Дата выхода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='version',
            field=models.CharField(default=' ', max_length=255, verbose_name='Версия продукта'),
            preserve_default=False,
        ),
    ]
