# Generated by Django 3.2.3 on 2021-05-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210526_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smartphone',
            new_name='Key',
        ),
    ]
