# Generated by Django 3.2.3 on 2021-05-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_rename_smartphone_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='accum_volume',
        ),
        migrations.RemoveField(
            model_name='key',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='key',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='key',
            name='frontal_cam_mp',
        ),
        migrations.RemoveField(
            model_name='key',
            name='main_cam_mp',
        ),
        migrations.RemoveField(
            model_name='key',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='key',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='key',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='key',
            name='sd_volume_max',
        ),
        migrations.AddField(
            model_name='key',
            name='activate',
            field=models.CharField(default=' ', max_length=255, verbose_name='Активация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='author',
            field=models.CharField(default=' ', max_length=255, verbose_name='Разработчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='genre',
            field=models.CharField(default=' ', max_length=255, verbose_name='Жанр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='is_key',
            field=models.BooleanField(default=True, verbose_name='Наличие ключей'),
        ),
        migrations.AddField(
            model_name='key',
            name='language',
            field=models.CharField(default=' ', max_length=255, verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='num_of_keys',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество ключей'),
        ),
        migrations.AddField(
            model_name='key',
            name='os',
            field=models.CharField(default=' ', max_length=255, verbose_name='ОС'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='relise',
            field=models.CharField(default=' ', max_length=255, verbose_name='Дата выхода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='version',
            field=models.CharField(default=' ', max_length=255, verbose_name='Версия продукта'),
            preserve_default=False,
        ),
    ]
