# Generated by Django 3.2.3 on 2021-05-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210526_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='is_key',
            field=models.BooleanField(default=True, verbose_name='Наличие ключей'),
        ),
        migrations.AlterField(
            model_name='key',
            name='num_of_keys',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество ключей'),
        ),
        migrations.AlterField(
            model_name='key',
            name='version',
            field=models.CharField(max_length=255, verbose_name='Версия продукта'),
        ),
        migrations.DeleteModel(
            name='Game_other',
        ),
    ]
