# Generated by Django 3.2.3 on 2021-05-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20210526_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('platform', models.CharField(max_length=255, verbose_name='Платформа')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('author', models.CharField(max_length=255, verbose_name='Издатель')),
                ('language', models.CharField(max_length=255, verbose_name='Язык')),
                ('relise', models.CharField(max_length=255, verbose_name='Дата выхода')),
                ('version', models.CharField(max_length=255, verbose_name='Версия продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
