# Generated by Django 3.2.3 on 2021-05-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='activate',
            field=models.CharField(max_length=255, verbose_name='Серия игр'),
        ),
        migrations.AlterField(
            model_name='key',
            name='is_key',
            field=models.BooleanField(default=True, verbose_name='Активация'),
        ),
        migrations.AlterField(
            model_name='key',
            name='num_of_keys',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метод активации'),
        ),
    ]
