# Generated by Django 3.0.8 on 2023-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210527_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stats',
            field=models.IntegerField(default=0, verbose_name='Статистика'),
        ),
        migrations.AddField(
            model_name='games',
            name='stats',
            field=models.IntegerField(default=0, verbose_name='Статистика'),
        ),
        migrations.AddField(
            model_name='key',
            name='stats',
            field=models.IntegerField(default=0, verbose_name='Статистика'),
        ),
    ]
