# Generated by Django 3.0.8 on 2023-04-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20230419_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='stats',
            field=models.IntegerField(verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='key',
            name='stats',
            field=models.IntegerField(verbose_name='Статистика'),
        ),
    ]
