# Generated by Django 3.0.8 on 2023-04-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20230419_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stats',
            field=models.IntegerField(verbose_name='Статистика'),
        ),
    ]
