# Generated by Django 3.0.8 on 2023-04-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20230419_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='games',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='key',
            name='stats',
        ),
    ]
