# Generated by Django 3.0.8 on 2023-04-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20230420_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_orders', to='mainapp.Order', verbose_name='Заказы'),
        ),
        migrations.AddField(
            model_name='games',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_orders', to='mainapp.Order', verbose_name='Заказы'),
        ),
        migrations.AddField(
            model_name='key',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_orders', to='mainapp.Order', verbose_name='Заказы'),
        ),
    ]
